// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWzcjDjsZw7kCfc-7gi8fmx4HfB7xfnG4',
    appId: '1:1013490159378:web:48e356f0d9ed4254672dcb',
    messagingSenderId: '1013490159378',
    projectId: 'diary-new-df7d3',
    authDomain: 'diary-new-df7d3.firebaseapp.com',
    storageBucket: 'diary-new-df7d3.firebasestorage.app',
    measurementId: 'G-KD07GC8DH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzXYWVFXunxIvXPeORJj7y37jievLJX5M',
    appId: '1:1013490159378:android:476ee895d47845cd672dcb',
    messagingSenderId: '1013490159378',
    projectId: 'diary-new-df7d3',
    storageBucket: 'diary-new-df7d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl8BJ34Zk9YerT_EzBLYzYENk1Sm4mFfc',
    appId: '1:1013490159378:ios:a495ef94b5a50911672dcb',
    messagingSenderId: '1013490159378',
    projectId: 'diary-new-df7d3',
    storageBucket: 'diary-new-df7d3.firebasestorage.app',
    iosBundleId: 'com.example.dearDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl8BJ34Zk9YerT_EzBLYzYENk1Sm4mFfc',
    appId: '1:1013490159378:ios:a495ef94b5a50911672dcb',
    messagingSenderId: '1013490159378',
    projectId: 'diary-new-df7d3',
    storageBucket: 'diary-new-df7d3.firebasestorage.app',
    iosBundleId: 'com.example.dearDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWzcjDjsZw7kCfc-7gi8fmx4HfB7xfnG4',
    appId: '1:1013490159378:web:59c5b2715cb1ef98672dcb',
    messagingSenderId: '1013490159378',
    projectId: 'diary-new-df7d3',
    authDomain: 'diary-new-df7d3.firebaseapp.com',
    storageBucket: 'diary-new-df7d3.firebasestorage.app',
    measurementId: 'G-SMFN22ERLS',
  );

}